[package]
name = "disk-archive"
version = "0.1.0"
authors = ["Wren Powell <wrentpowell@gmail.com>"]
edition = "2018"

[dependencies]
multihash = "0.8.0"
diesel = { version = "1.4.3", features = ["sqlite"] }
diesel_migrations = "1.4.0"
blake2-rfc = "0.2.18"
xattr = "0.2.2"
flate2 = "1.0.13"
fuse = "0.3.1"
zip = "0.5.3"
clap = "2.33.0"
thiserror = "1.0.4"
anyhow = "1.0.19"
chrono = "0.4.10"
futures = "0.3.1"
