[package]
name = "disk-archive"
version = "0.1.0"
authors = ["Wren Powell <wrentpowell@gmail.com>"]
edition = "2018"

[dependencies]
# File I/O
xattr = "0.2.2"
filetime = "0.2.8"
fuse = "0.3.1"
relative-path = "1.0.0"
walkdir = "2.2.9"
tempfile = "3.1.0"

# Hashing
blake2 = "0.8.1"

# Compression
flate2 = "1.0.13"
xz2 = "0.1.6"

# Encryption
sodiumoxide = "0.2.5"
secstr = "0.3.2"

# Error handling
thiserror = "1.0.4"
anyhow = "1.0.19"

# Serialization
serde = { version = "1.0.103", features = ["derive"] }
rmp = "0.8.8"
rmp-serde = "0.14.0"

# Misc
num-integer = "0.1.41"
uuid = "0.8.1"
