[package]
name = "data-store"
version = "0.1.0"
authors = ["Wren Powell <wrentpowell@gmail.com>"]
edition = "2018"

[dependencies]
# File system
filetime = "0.2.8"
relative-path = "1.0.0"
walkdir = "2.2.9"
fs2 = "0.4.3"
dirs = "2.0.2"

# I/O
cdchunking = "1.0.0"

# SQL
rusqlite = { version = "0.21.0", features = ["bundled"] }

# Hashing
blake2 = "0.8.1"

# Error handling
thiserror = "1.0.9"
anyhow = "1.0.26"

# Compression
flate2 = "1.0.13"
xz2 = "0.1.6"
lz4 = "1.23.1"

# Encryption
sodiumoxide = "0.2.5"
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }
rand = { version = "0.7.2", features = ["small_rng"] }

# Serialization
serde = { version = "1.0.103", features = ["derive"] }
rmp = "0.8.8"
rmp-serde = "0.14.0"

# Misc
uuid = { version = "0.8.1", features = ["serde", "v4"] }
lazy_static = "1.4.0"
weak-table = "0.2.3"

# Unix-specific
[target.'cfg(unix)'.dependencies]
fuse = "0.3.1"
xattr = "0.2.2"
